"use client";
import { useCallback, useEffect, useState } from 'react';
import { getAuth } from 'firebase/auth';
import { toast } from 'react-hot-toast';
import type { DateRange, Granularity, KPISet } from '@/lib/analytics-aggregations';
import type { Order } from '@/types';

type View = { id: string; name: string; range: DateRange; granularity: Granularity };
type Targets = { revenue: number; paidOrders: number; conversionRate: number };
const emptyTargets: Targets = { revenue: 0, paidOrders: 0, conversionRate: 0 };

export default function AnalyticsWorkspaceControls({ range, granularity, onApplyView, kpis, orders }: { range: DateRange; granularity: Granularity; onApplyView: (range: DateRange, granularity: Granularity) => void; kpis: KPISet; orders: Order[] }) {
  const [views, setViews] = useState<View[]>([]); const [targets, setTargets] = useState<Targets>(emptyTargets); const [editingTargets, setEditingTargets] = useState(false); const [saving, setSaving] = useState(false);
  const request = useCallback(async (init?: RequestInit) => { const token = await getAuth().currentUser?.getIdToken(); if (!token) throw new Error('Admin session unavailable'); const response = await fetch('/api/admin/analytics/preferences', { ...init, headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` } }); const data = await response.json(); if (!response.ok) throw new Error(data.message || 'Request failed'); return data; }, []);
  useEffect(() => { request().then((data) => { setViews(data.preferences?.views || []); setTargets({ ...emptyTargets, ...(data.preferences?.targets || {}) }); }).catch(() => undefined); }, [request]);
  async function persist(nextViews = views, nextTargets = targets) { setSaving(true); try { await request({ method: 'PUT', body: JSON.stringify({ views: nextViews, targets: nextTargets }) }); setViews(nextViews); setTargets(nextTargets); toast.success('Analytics workspace saved'); } catch (error) { toast.error(error instanceof Error ? error.message : 'Save failed'); } finally { setSaving(false); } }
  async function saveView() { const name = window.prompt('Name this dashboard view:')?.trim(); if (!name) return; const next = [...views.filter((view) => view.name.toLowerCase() !== name.toLowerCase()), { id: `view_${Date.now()}`, name, range, granularity }].slice(-12); await persist(next, targets); }
  function exportCsv() { const rows = [['Order ID', 'Date', 'Customer', 'County', 'Payment method', 'Payment status', 'Fulfilment status', 'Total'], ...orders.map((order) => [order.id, order.date, order.userName || order.userEmail || order.userId, order.shippingAddress?.county || '', order.paymentMethod || '', order.paymentStatus || 'Unpaid', order.status, String(order.total)])]; const csv = rows.map((row) => row.map((value) => `"${String(value).replace(/"/g, '""')}"`).join(',')).join('\r\n'); const blob = new Blob([csv], { type: 'text/csv;charset=utf-8' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `melagri-analytics-${range}-${new Date().toISOString().slice(0, 10)}.csv`; link.click(); URL.revokeObjectURL(url); }
  const targetItems = [{ key: 'revenue' as const, label: 'Revenue target', actual: kpis.revenue, format: (value: number) => `KES ${Math.round(value).toLocaleString()}` }, { key: 'paidOrders' as const, label: 'Paid-order target', actual: kpis.paidCount, format: (value: number) => Math.round(value).toLocaleString() }, { key: 'conversionRate' as const, label: 'Conversion target', actual: kpis.conversionRate, format: (value: number) => `${value.toFixed(1)}%` }];
  return <div className="space-y-4"><div className="flex flex-col gap-3 rounded-2xl border border-gray-200 bg-white p-4 shadow-sm lg:flex-row lg:items-center lg:justify-between"><div className="flex min-w-0 flex-wrap items-center gap-2"><span className="mr-1 text-[10px] font-black uppercase tracking-wider text-gray-400">Saved views</span>{views.length === 0 ? <span className="text-xs text-gray-400">No views saved</span> : views.map((view) => <button key={view.id} type="button" onClick={() => onApplyView(view.range, view.granularity)} className="rounded-full border border-gray-200 px-3 py-1.5 text-xs font-bold text-gray-700 hover:border-green-500 hover:text-green-700">{view.name}</button>)}</div><div className="flex flex-wrap gap-2"><button type="button" onClick={saveView} disabled={saving} className="min-h-10 rounded-lg border border-gray-200 px-3 text-xs font-black text-gray-700">Save current view</button><button type="button" onClick={() => setEditingTargets((value) => !value)} className="min-h-10 rounded-lg border border-gray-200 px-3 text-xs font-black text-gray-700">Set targets</button><button type="button" onClick={exportCsv} className="min-h-10 rounded-lg bg-gray-950 px-4 text-xs font-black text-white hover:bg-green-700">Export CSV</button></div></div>
  {editingTargets && <div className="grid gap-3 rounded-2xl border border-blue-200 bg-blue-50 p-4 sm:grid-cols-3">{targetItems.map((item) => <label key={item.key} className="text-[10px] font-black uppercase tracking-wider text-blue-800">{item.label}<input type="number" min="0" max={item.key === 'conversionRate' ? 100 : undefined} value={targets[item.key]} onChange={(event) => setTargets((current) => ({ ...current, [item.key]: Number(event.target.value) }))} className="mt-1 min-h-11 w-full rounded-xl border border-blue-200 bg-white px-3 text-sm font-bold text-gray-900" /></label>)}<div className="sm:col-span-3 flex justify-end"><button type="button" onClick={() => persist(views, targets).then(() => setEditingTargets(false))} disabled={saving} className="rounded-lg bg-blue-700 px-4 py-2 text-xs font-black text-white">{saving ? 'Saving...' : 'Save targets'}</button></div></div>}
  <div className="grid gap-3 sm:grid-cols-3">{targetItems.map((item) => { const target = targets[item.key]; const progress = target > 0 ? Math.min(100, item.actual / target * 100) : 0; return <div key={item.key} className="rounded-2xl border border-gray-200 bg-white p-4"><div className="flex items-center justify-between gap-3"><p className="text-xs font-bold text-gray-500">{item.label}</p><span className="text-[10px] font-black text-green-700">{target > 0 ? `${progress.toFixed(0)}%` : 'Not set'}</span></div><p className="mt-1 font-black text-gray-950">{item.format(item.actual)}{target > 0 && <span className="font-medium text-gray-400"> / {item.format(target)}</span>}</p><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-gray-100"><div className="h-full rounded-full bg-green-600 transition-[width]" style={{ width: `${progress}%` }} /></div></div>; })}</div></div>;
}
