"use client";
import { useCallback, useEffect, useState } from "react";
import { getAuth } from "firebase/auth";
import { toast } from "react-hot-toast";

type Discount = { id: string; code: string; type: "PERCENTAGE" | "FIXED_AMOUNT"; value: number; minOrderValue?: number; usageLimit?: number | null; usedCount?: number; expiresAt: string; isActive: boolean };
const emptyForm = { code: "", type: "PERCENTAGE", value: "", minOrderValue: "", usageLimit: "", expiresAt: "" };

export default function DiscountManagementPage() {
  const [discounts, setDiscounts] = useState<Discount[]>([]); const [form, setForm] = useState(emptyForm); const [creating, setCreating] = useState(false); const [saving, setSaving] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [cursor, setCursor] = useState<string | null>(null); const [history, setHistory] = useState<Array<string | null>>([]); const [nextCursor, setNextCursor] = useState<string | null>(null); const [refreshKey, setRefreshKey] = useState(0);
  const request = useCallback(async (body?: Record<string, unknown>) => { const token = await getAuth().currentUser?.getIdToken(); if (!token) throw new Error("Admin session is unavailable."); const response = await fetch(body ? "/api/admin/discounts" : `/api/admin/discounts${cursor ? `?cursor=${encodeURIComponent(cursor)}` : ""}`, { method: body ? "POST" : "GET", headers: { ...(body ? { "Content-Type": "application/json" } : {}), Authorization: `Bearer ${token}` }, ...(body ? { body: JSON.stringify(body) } : {}) }); const result = await response.json(); if (!response.ok) throw new Error(result.message || "Discount request failed."); return result; }, [cursor]);
  useEffect(() => { let cancelled = false; setLoading(true); setError(""); request().then((result) => { if (!cancelled) { setDiscounts(result.discounts || []); setNextCursor(result.nextCursor || null); } }).catch((caught) => { if (!cancelled) setError(caught instanceof Error ? caught.message : "Could not load discounts."); }).finally(() => { if (!cancelled) setLoading(false); }); return () => { cancelled = true; }; }, [request, refreshKey]);
  async function create(event: React.FormEvent) { event.preventDefault(); setSaving(true); try { await request({ action: "create", code: form.code, type: form.type, value: Number(form.value), minOrderValue: Number(form.minOrderValue || 0), usageLimit: form.usageLimit ? Number(form.usageLimit) : null, expiresAt: new Date(`${form.expiresAt}T23:59:59.999Z`).toISOString() }); toast.success("Discount created"); setForm(emptyForm); setCreating(false); setCursor(null); setHistory([]); setRefreshKey((value) => value + 1); } catch (caught) { toast.error(caught instanceof Error ? caught.message : "Could not create discount."); } finally { setSaving(false); } }
  async function lifecycle(discount: Discount, action: "activate" | "deactivate" | "archive") { if (action === "archive" && !window.confirm(`Archive ${discount.code}? Existing order history will be preserved.`)) return; setSaving(true); try { await request({ action, discountId: discount.id }); toast.success(action === "archive" ? "Discount archived" : `Discount ${action}d`); setRefreshKey((value) => value + 1); } catch (caught) { toast.error(caught instanceof Error ? caught.message : "Update failed."); } finally { setSaving(false); } }
  return <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><header><p className="mb-1 text-[10px] font-black uppercase tracking-[.18em] text-green-700">Catalogue growth</p><h1 className="text-2xl font-black text-gray-950">Discount codes</h1><p className="mt-1 text-sm text-gray-500">Create controlled promotions without losing historical usage evidence.</p></header><button onClick={() => setCreating((value) => !value)} className="min-h-11 rounded-xl bg-green-700 px-5 text-sm font-black text-white">{creating ? "Cancel" : "Create discount"}</button></div>
    {creating && <form onSubmit={create} className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3"><Field label="Code"><input required pattern="[A-Za-z0-9_-]{3,30}" value={form.code} onChange={(event) => setForm({ ...form, code: event.target.value.toUpperCase() })} placeholder="PLANTING10" className="input"/></Field><Field label="Expiry"><input required type="date" min={new Date().toISOString().slice(0, 10)} value={form.expiresAt} onChange={(event) => setForm({ ...form, expiresAt: event.target.value })} className="input"/></Field><Field label="Type"><select value={form.type} onChange={(event) => setForm({ ...form, type: event.target.value })} className="input"><option value="PERCENTAGE">Percentage</option><option value="FIXED_AMOUNT">Fixed amount</option></select></Field><Field label="Value"><input required type="number" min="0.01" max={form.type === "PERCENTAGE" ? 100 : 1000000} step="0.01" value={form.value} onChange={(event) => setForm({ ...form, value: event.target.value })} className="input"/></Field><Field label="Minimum order"><input type="number" min="0" value={form.minOrderValue} onChange={(event) => setForm({ ...form, minOrderValue: event.target.value })} className="input"/></Field><Field label="Usage limit"><input type="number" min="1" value={form.usageLimit} onChange={(event) => setForm({ ...form, usageLimit: event.target.value })} placeholder="Unlimited" className="input"/></Field></div><div className="mt-5 flex justify-end"><button disabled={saving} className="min-h-11 rounded-xl bg-gray-950 px-5 text-sm font-black text-white disabled:opacity-40">{saving ? "Creating…" : "Create code"}</button></div></form>}
    {error && <p className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</p>}<section className="overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[820px] text-left text-sm"><thead className="border-b bg-gray-50 text-[10px] font-black uppercase tracking-wider text-gray-500"><tr><th className="px-5 py-3">Code</th><th>Benefit</th><th>Minimum</th><th>Usage</th><th>Expiry</th><th>Status</th><th className="px-5 text-right">Actions</th></tr></thead><tbody className="divide-y">{!loading && discounts.map((discount) => { const expired = Date.parse(discount.expiresAt) < Date.now(); return <tr key={discount.id}><td className="px-5 py-4 font-black">{discount.code}</td><td className="font-bold text-green-700">{discount.type === "PERCENTAGE" ? `${discount.value}%` : `KES ${discount.value.toLocaleString()}`}</td><td>{discount.minOrderValue ? `KES ${discount.minOrderValue.toLocaleString()}` : "None"}</td><td>{discount.usedCount || 0} / {discount.usageLimit || "∞"}</td><td>{new Date(discount.expiresAt).toLocaleDateString()}</td><td><span className={`rounded-full px-2 py-1 text-[10px] font-black uppercase ${expired ? "bg-red-50 text-red-700" : discount.isActive ? "bg-green-50 text-green-700" : "bg-gray-100 text-gray-600"}`}>{expired ? "Expired" : discount.isActive ? "Active" : "Inactive"}</span></td><td className="space-x-2 px-5 text-right"><button disabled={saving || expired} onClick={() => lifecycle(discount, discount.isActive ? "deactivate" : "activate")} className="rounded-lg px-2 py-2 text-xs font-bold text-gray-600 hover:bg-gray-100 disabled:opacity-40">{discount.isActive ? "Pause" : "Activate"}</button><button disabled={saving} onClick={() => lifecycle(discount, "archive")} className="rounded-lg px-2 py-2 text-xs font-bold text-red-600 hover:bg-red-50">Archive</button></td></tr>; })}</tbody></table></div>{loading ? <Empty>Loading discounts…</Empty> : discounts.length === 0 && !error ? <Empty>No discount codes found.</Empty> : <footer className="flex items-center justify-between border-t p-4 text-xs text-gray-500"><span>Page {history.length + 1}</span><div className="flex gap-2"><button disabled={history.length === 0} onClick={() => setHistory((current) => { const copy = [...current]; setCursor(copy.pop() ?? null); return copy; })} className="rounded-lg border px-3 py-2 font-bold disabled:opacity-40">Previous</button><button disabled={!nextCursor} onClick={() => { if (nextCursor) { setHistory((current) => [...current, cursor]); setCursor(nextCursor); } }} className="rounded-lg border px-3 py-2 font-bold disabled:opacity-40">Next</button></div></footer>}</section>
  </div>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="text-xs font-black text-gray-600">{label}<div className="mt-2 [&_.input]:min-h-11 [&_.input]:w-full [&_.input]:rounded-xl [&_.input]:border [&_.input]:border-gray-200 [&_.input]:px-3 [&_.input]:text-sm [&_.input]:font-semibold [&_.input]:outline-none">{children}</div></label>; }
function Empty({ children }: { children: React.ReactNode }) { return <p className="p-14 text-center text-sm text-gray-500">{children}</p>; }
