"use client";
import { useEffect, useState } from 'react';
import { getAuth } from 'firebase/auth';
import { toast } from 'react-hot-toast';

interface Data { generatedAt: string; sourceWindow: { orders: number; products: number; searches: number }; demandGaps: Array<{ term: string; searches: number; opportunity: string; closestProduct?: string }>; inventory: Array<{ productId: string; name: string; stock: number; incomingStock: number; supplierLeadTimeDays: number; daysOfCover: number | null; reorderPoint: number; recommendedOrderQuantity: number; reorderNow: boolean; confidence: string; reason: string }>; performance: Array<{ productId: string; views: number; carts: number; cartRate: number }> }

export default function ProductIntelligencePage() {
    const [data, setData] = useState<Data | null>(null);
    const [loading, setLoading] = useState(true);
    useEffect(() => { (async () => { try { const token = await getAuth().currentUser?.getIdToken(); if (!token) throw new Error('Admin session unavailable'); const response = await fetch('/api/admin/intelligence/products', { headers: { Authorization: `Bearer ${token}` } }); const result = await response.json(); if (!response.ok) throw new Error(result.message); setData(result); } catch (error) { toast.error(error instanceof Error ? error.message : 'Unable to load product intelligence'); } finally { setLoading(false); } })(); }, []);
    if (loading) return <div className="rounded-2xl bg-white p-12 text-center text-gray-500">Building product intelligence…</div>;
    if (!data) return <div className="rounded-2xl border border-red-100 bg-red-50 p-8 text-red-700">Product intelligence is unavailable.</div>;
    const reorder = data.inventory.filter(item => item.reorderNow);
    return <div className="space-y-8 pb-12">
        <header><p className="text-[10px] font-black uppercase tracking-[0.22em] text-emerald-700">Catalog and supply decisions</p><h1 className="mt-1 text-3xl font-black tracking-tight text-gray-900">Product Intelligence</h1><p className="mt-1 text-sm text-gray-500">Evidence from {data.sourceWindow.orders} orders, {data.sourceWindow.products} products, and {data.sourceWindow.searches} search terms.</p></header>
        <div className="grid gap-4 md:grid-cols-3"><div className="rounded-2xl border border-red-100 bg-red-50 p-5"><p className="text-xs font-bold text-red-600">Reorder now</p><p className="mt-1 text-3xl font-black text-red-800">{reorder.length}</p></div><div className="rounded-2xl border border-amber-100 bg-amber-50 p-5"><p className="text-xs font-bold text-amber-700">Unmet searches</p><p className="mt-1 text-3xl font-black text-amber-900">{data.demandGaps.length}</p></div><div className="rounded-2xl border border-gray-100 bg-white p-5"><p className="text-xs font-bold text-gray-400">Generated</p><p className="mt-2 text-sm font-black text-gray-800">{new Date(data.generatedAt).toLocaleString()}</p></div></div>
        <section className="rounded-3xl border border-gray-100 bg-white p-6 md:p-8"><h2 className="text-xl font-black text-gray-900">Supply recommendations</h2><p className="mt-1 text-sm text-gray-500">Uses paid demand, incoming stock, safety stock, supplier lead time, and MOQ.</p><div className="mt-6 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b text-[10px] uppercase tracking-widest text-gray-400"><tr><th className="py-3">Product</th><th>Cover</th><th>Lead time</th><th>Reorder point</th><th>Suggested PO</th><th>Confidence</th></tr></thead><tbody className="divide-y">{data.inventory.slice(0, 40).map(item => <tr key={item.productId} className={item.reorderNow ? 'bg-red-50/40' : ''}><td className="py-4 font-bold text-gray-900">{item.name}<span className="block max-w-sm text-xs font-normal text-gray-500">{item.reason}</span></td><td>{item.daysOfCover === null ? 'No velocity' : `${item.daysOfCover}d`}</td><td>{item.supplierLeadTimeDays}d</td><td>{item.reorderPoint}</td><td className="font-black text-emerald-700">{item.recommendedOrderQuantity || '—'}</td><td className="uppercase text-xs font-bold text-gray-500">{item.confidence}</td></tr>)}</tbody></table></div></section>
        <section className="rounded-3xl border border-gray-100 bg-white p-6 md:p-8"><h2 className="text-xl font-black text-gray-900">Search demand gaps</h2><p className="mt-1 text-sm text-gray-500">Customer searches without a confident catalog match.</p>{data.demandGaps.length ? <div className="mt-5 grid gap-3 md:grid-cols-2">{data.demandGaps.map(gap => <article key={gap.term} className="rounded-2xl bg-amber-50 p-4"><div className="flex justify-between gap-3"><h3 className="font-black text-gray-900">“{gap.term}”</h3><span className="text-xs font-black text-amber-800">{gap.searches} searches</span></div><p className="mt-1 text-xs text-gray-600">{gap.opportunity === 'missing_product' ? 'No catalog match' : `Weak match: ${gap.closestProduct}`}</p></article>)}</div> : <p className="mt-5 rounded-xl bg-emerald-50 p-5 text-sm font-bold text-emerald-800">Current top searches have catalog matches.</p>}</section>
    </div>;
}
