"use client";
import { useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import { getAuth } from 'firebase/auth';
import { toast } from 'react-hot-toast';
import type { AutomationRule } from '@/lib/automation-rules';

type Run = { id: string; generated?: number; rulesEvaluated?: string[]; status?: string; createdAt?: { seconds?: number } };
async function request(path: string, init?: RequestInit) { const token = await getAuth().currentUser?.getIdToken(); if (!token) throw new Error('Admin session unavailable'); const response = await fetch(path, { ...init, headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}`, ...(init?.headers || {}) } }); const data = await response.json(); if (!response.ok) throw new Error(data.message || 'Request failed'); return data; }

export default function AutomationsPage() {
  const [rules, setRules] = useState<AutomationRule[]>([]); const [runs, setRuns] = useState<Run[]>([]); const [loading, setLoading] = useState(true); const [running, setRunning] = useState(false); const [saving, setSaving] = useState<string | null>(null);
  const load = useCallback(async () => { try { const data = await request('/api/admin/automations'); setRules(data.rules || []); setRuns(data.runs || []); } catch (error) { toast.error(error instanceof Error ? error.message : 'Could not load automations'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const updateLocal = (key: string, patch: Partial<AutomationRule>) => setRules((current) => current.map((rule) => rule.key === key ? { ...rule, ...patch } : rule));
  async function save(rule: AutomationRule) { setSaving(rule.key); try { await request('/api/admin/automations', { method: 'PUT', body: JSON.stringify(rule) }); toast.success(`${rule.name} saved`); await load(); } catch (error) { toast.error(error instanceof Error ? error.message : 'Save failed'); } finally { setSaving(null); } }
  async function runNow() { setRunning(true); try { const result = await request('/api/admin/automations', { method: 'POST' }); toast.success(`${result.generated} operational tasks generated`); await load(); } catch (error) { toast.error(error instanceof Error ? error.message : 'Automation run failed'); } finally { setRunning(false); } }
  const enabled = rules.filter((rule) => rule.enabled).length;
  return <div className="space-y-6"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-green-700">Controlled operations</p><h1 className="mt-1 text-3xl font-black tracking-tight text-gray-950">Automation centre</h1><p className="mt-1 max-w-2xl text-sm text-gray-500">Turn repeatable signals into assigned work without removing human approval from customer contact or stock decisions.</p></div><button type="button" onClick={runNow} disabled={running || loading} className="min-h-11 rounded-xl bg-gray-950 px-5 text-xs font-black uppercase tracking-wider text-white hover:bg-green-700 disabled:opacity-50">{running ? 'Running checks...' : 'Run automations now'}</button></header>
  <div className="grid gap-4 sm:grid-cols-3"><div className="rounded-2xl border border-gray-200 bg-white p-5"><p className="text-xs font-bold text-gray-400">Enabled rules</p><p className="mt-1 text-3xl font-black">{enabled}<span className="text-base text-gray-400">/{rules.length}</span></p></div><div className="rounded-2xl border border-gray-200 bg-white p-5"><p className="text-xs font-bold text-gray-400">Last run output</p><p className="mt-1 text-3xl font-black">{runs[0]?.generated || 0}</p></div><Link href="/dashboard/admin/action-centre" className="rounded-2xl border border-green-200 bg-green-50 p-5 transition hover:border-green-400"><p className="text-xs font-bold text-green-700">Human review queue</p><p className="mt-2 font-black text-green-950">Open Action Centre →</p></Link></div>
  {loading ? <div className="rounded-2xl bg-white p-12 text-center text-sm text-gray-500">Loading automation rules...</div> : <div className="grid gap-4 lg:grid-cols-2">{rules.map((rule) => <article key={rule.key} className={`rounded-2xl border bg-white p-5 shadow-sm ${rule.enabled ? 'border-green-200' : 'border-gray-200'}`}><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2"><h2 className="font-black text-gray-950">{rule.name}</h2><span className={`rounded-full px-2 py-0.5 text-[9px] font-black uppercase ${rule.mode === 'assisted' ? 'bg-blue-50 text-blue-700' : 'bg-gray-100 text-gray-600'}`}>{rule.mode.replace('_', ' ')}</span></div><p className="mt-1 text-sm leading-6 text-gray-500">{rule.description}</p></div><button type="button" role="switch" aria-checked={rule.enabled} aria-label={`${rule.enabled ? 'Disable' : 'Enable'} ${rule.name}`} onClick={() => updateLocal(rule.key, { enabled: !rule.enabled })} className={`relative h-7 w-12 shrink-0 rounded-full transition ${rule.enabled ? 'bg-green-700' : 'bg-gray-300'}`}><span className={`absolute top-1 h-5 w-5 rounded-full bg-white shadow transition-transform ${rule.enabled ? 'translate-x-6' : 'translate-x-1'}`} /></button></div><div className="mt-5 grid grid-cols-2 gap-3"><label className="text-[10px] font-black uppercase tracking-wider text-gray-500">{rule.thresholdLabel}<input type="number" min="1" max="10080" value={rule.threshold} onChange={(event) => updateLocal(rule.key, { threshold: Number(event.target.value) })} className="mt-1 min-h-11 w-full rounded-xl border border-gray-200 px-3 text-sm font-bold text-gray-900" /></label><label className="text-[10px] font-black uppercase tracking-wider text-gray-500">Operating mode<select value={rule.mode} onChange={(event) => updateLocal(rule.key, { mode: event.target.value as AutomationRule['mode'] })} className="mt-1 min-h-11 w-full rounded-xl border border-gray-200 px-3 text-sm font-bold text-gray-900"><option value="alert_only">Alert only</option><option value="assisted">Assisted action</option></select></label></div><div className="mt-4 flex items-center justify-between"><p className="text-[10px] font-semibold text-gray-400">Changes take effect after saving.</p><button type="button" onClick={() => save(rule)} disabled={saving === rule.key} className="rounded-lg border border-gray-200 px-4 py-2 text-xs font-black text-gray-700 hover:border-green-500 hover:text-green-700 disabled:opacity-50">{saving === rule.key ? 'Saving...' : 'Save rule'}</button></div></article>)}</div>}
  <section className="overflow-hidden rounded-2xl border border-gray-200 bg-white"><div className="border-b border-gray-100 px-5 py-4"><h2 className="font-black text-gray-950">Recent runs</h2></div>{runs.length === 0 ? <p className="p-6 text-sm text-gray-500">No automation runs recorded yet.</p> : <div className="divide-y divide-gray-100">{runs.map((run) => <div key={run.id} className="flex items-center justify-between gap-4 px-5 py-4"><div><p className="text-sm font-bold text-gray-900">{run.rulesEvaluated?.length || 0} rules evaluated</p><p className="text-xs text-gray-400">Run {run.id.slice(0, 10)}</p></div><span className="rounded-full bg-green-50 px-3 py-1 text-xs font-black text-green-700">{run.generated || 0} tasks</span></div>)}</div>}</section></div>;
}
